# Generated by Django 3.2.4 on 2021-11-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('date', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=30)),
                ('counterman', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=30)),
                ('plan_date_sample', models.DateField()),
                ('report_agree_date', models.DateField()),
                ('number_of_reports', models.CharField(max_length=5)),
                ('test_style', models.CharField(max_length=5)),
                ('report_type', models.CharField(max_length=5)),
                ('quality_control_report', models.CharField(max_length=2)),
                ('split_or_not', models.CharField(max_length=2)),
                ('subpackage_or_not', models.CharField(max_length=2)),
                ('mission_link', models.CharField(max_length=100)),
                ('voluntary_standards', models.CharField(max_length=255)),
                ('collector', models.CharField(max_length=25)),
                ('sample_date', models.DateField()),
                ('progress', models.CharField(max_length=5)),
                ('status_bar', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
