# Generated by Django 3.2.4 on 2021-11-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projinfo',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='plan_date_sample',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='report_agree_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='sample_date',
            field=models.CharField(max_length=20),
        ),
    ]
