# Generated by Django 3.2.4 on 2021-11-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
