# Generated by Django 3.2.4 on 2021-11-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_samplehandover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplehandover',
            old_name='project_id',
            new_name='samplehandover_to_project_id',
        ),
        migrations.RenameField(
            model_name='samplehandover',
            old_name='sample_type',
            new_name='samplehandover_to_sample_type',
        ),
        migrations.RenameField(
            model_name='samplehandover',
            old_name='storage',
            new_name='samplehandover_to_storage',
        ),
    ]
