# Generated by Django 3.2.4 on 2021-11-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20211102_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplehandover',
            old_name='samplehandover_to_project_id',
            new_name='sh_pid',
        ),
        migrations.RenameField(
            model_name='samplehandover',
            old_name='samplehandover_to_sample_type',
            new_name='sh_spt',
        ),
        migrations.RenameField(
            model_name='samplehandover',
            old_name='samplehandover_to_storage',
            new_name='sh_sto',
        ),
    ]
