# Generated by Django 3.2.4 on 2021-11-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20211102_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleHandover',
        ),
    ]
