# Generated by Django 3.2.4 on 2021-11-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_delete_samplehandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ids', models.CharField(max_length=105)),
                ('analysis_items', models.CharField(max_length=255)),
                ('sample_number', models.CharField(max_length=5)),
                ('char_person', models.CharField(max_length=15)),
                ('status_bar', models.CharField(max_length=2)),
                ('sh_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.projinfo')),
                ('sh_spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sampletype')),
                ('sh_sto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.storage')),
            ],
        ),
    ]
