# Generated by Django 3.2.4 on 2021-11-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_samplehandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=20, unique=True)),
                ('sampling_position', models.CharField(max_length=20)),
                ('coordinate', models.CharField(max_length=30)),
                ('analysis_items', models.CharField(max_length=255)),
                ('sampling_date', models.CharField(max_length=20)),
                ('sampling_of_days', models.CharField(max_length=2)),
                ('sample_traits', models.CharField(max_length=50)),
                ('status_bar', models.CharField(max_length=2)),
                ('si_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.projinfo')),
                ('si_spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sampletype')),
            ],
        ),
    ]
